### ISSUE TITLE
Scrum update 1

### ISSUE THREAD

**Issue by yahuizhan** [qlnjq/JustWorkIt#2]
In the past two weeks, I helped with raising ideas and deciding the topic of our website and helped determine the major functionalities of our website with my teammates. The major challenge was how features that are not supported by most APIs could be incorporated. My focus for the next following two weeks will be helping construct the home page, including the components of the home page and the clickable figure of human body, and helping collect/import data. (by k0t0b)

**Comment by JingwenB** [comment]
![image](https://user-images.githubusercontent.com/33404097/82744887-23ef4e00-9d33-11ea-9f7b-7dddbbc2a166.png)

**Comment by Mengmeng-Astrid** [comment]
For the last two weeks, we worked out the project idea and decided what the structure and topic of our project would be. The major challenge for me is to imagine how this product would look like and take both techniques and user experience into consideration at the same time. And also how to find a balance point of the imaginary and our workability. My focus for the next two weeks will be picking up new skills and apply them to build our home page. (m0g1b)

**Comment by qlnjq** [comment]
Since the project started, we have chosen one idea from the few that we have thought about and brainstorm features that might be interested to have. Thinking from the customer/user point of view, we then picked the ones that we think would be most helpful to the users. One major challenge for me is to think about the flow of the features, i.e. how to connect the features together and make it more user friendly without making the users think that it is frustrating how the things are presented on the screen. My focus for the next period will be visiting different user-interactive websites and be inspired about how their features are positioned to help develop our own website. (n6h1b)

**Comment by hailin-zhang** [comment]
great work guys! got you down :) feel free to close the issue
